### ISSUE TITLE
dashboard会自动运行？

### ISSUE THREAD

**Issue by DotWho** [yuanlam/Clash-Linux#1]
dashboard这边没弄明白，不需要挂ngnix？

**Comment by yuanlam** [comment]
> dashboard这边没弄明白，不需要挂ngnix？

会的哈，试过反复重启都没问题

**Comment by weironz** [comment]
linux下怎么安装clash dashboard

**Comment by hellodk34** [comment]
> linux下怎么安装clash dashboard

`wget https://github.com/haishanh/yacd/archive/gh-pages.zip`

这个 repo 中有写，可以再仔细读一下。 @willzhang
